---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./manager
  - ./webhook
  - ./scripts
  - ./quickstart.yaml
  - ./rbac

commonLabels:
  app: model-mesh
  app.kubernetes.io/part-of: model-mesh

configurations:
  - params.yaml
