apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: opendatahub
  namespace: %controller-namespace%
spec:
  applications:
    - kustomizeConfig:
        repoRef:
          name: odh-manifests
          path: odh-common
      name: odh-common
    - kustomizeConfig:
        parameters:
          - name: odh-mm-rest-proxy
            value: quay.io/opendatahub/rest-proxy:v0.11.0
          - name: odh-modelmesh-runtime-adapter
            value: quay.io/opendatahub/modelmesh-runtime-adapter:v0.11.0
          - name: odh-modelmesh
            value: quay.io/opendatahub/modelmesh:v0.11.0
          - name: odh-modelmesh-controller
            value: quay.io/opendatahub/modelmesh-controller:v0.11.0
          - name: odh-model-controller
            value: quay.io/opendatahub/odh-model-controller:v0.11.0
          - name: monitoring-namespace
            value: %controller-namespace%
        repoRef:
          name: manifests
          path: opendatahub/odh-manifests/model-mesh
      name: model-mesh
  repos:
    - name: odh-manifests
      uri: https://api.github.com/repos/opendatahub-io/odh-manifests/tarball/master
    - name: manifests
      uri: file:///tmp/odh-manifests.gzip
  version: master
