$patch: replace
apiVersion: apps/v1
kind: Deployment
metadata:
  name: modelmesh-controller
spec:
  replicas: 3
  template:
    spec:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - amd64
      containers:
        - image: $(odh-modelmesh-controller)
          resources:
            limits:
              memory: 2Gi