$patch: replace
apiVersion: v1
kind: Service
metadata:
  name: modelmesh-webhook-server-service
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
    service.beta.openshift.io/serving-cert-secret-name: modelmesh-webhook-server-cert