---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./service.yaml

configMapGenerator:
  - files:
      - config-defaults.yaml
    name: model-serving-config-defaults

generatorOptions:
  disableNameSuffixHash: true