name: Kube-linter
on:
  push:
    branches:
      - 'main'
      - 'imageshatag'
    paths:
      - '**'
      - '!.github/**'
      - '!.tekton/**'
      - '!docs/**'
      - '!**.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18.7'
      - name: Install kube-linter
        run: |
          go install golang.stackrox.io/kube-linter/cmd/kube-linter@latest
      - name: Run linter
        run: |
          kube-linter lint config/dependencies/quickstart.yaml
